"""Change name Set to Cardset

Revision ID: 02194f2d6cdf
Revises: f56c3d2e4ec0
Create Date: 2022-11-06 10:37:52.639871

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "02194f2d6cdf"
down_revision = "f56c3d2e4ec0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_cardset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["tb_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tb_cardset_id"), "tb_cardset", ["id"], unique=False)
    op.drop_index("ix_tb_set_id", table_name="tb_set")
    op.drop_table("tb_set")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_set",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["tb_user.id"], name="tb_set_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="tb_set_pkey"),
    )
    op.create_index("ix_tb_set_id", "tb_set", ["id"], unique=False)
    op.drop_index(op.f("ix_tb_cardset_id"), table_name="tb_cardset")
    op.drop_table("tb_cardset")
    # ### end Alembic commands ###
