"""Changed user data to include created_on and updated_on

Revision ID: 3c1590ccb769
Revises: 76578d9ccbfe
Create Date: 2022-11-02 09:27:52.137175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c1590ccb769"
down_revision = "76578d9ccbfe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_user", sa.Column("created_on", sa.DateTime(), nullable=True))
    op.add_column("tb_user", sa.Column("updated_on", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_user", "updated_on")
    op.drop_column("tb_user", "created_on")
    # ### end Alembic commands ###
